### ISSUE TITLE
When display a Journey, sometimes, start and stop icons are not shown

### ISSUE THREAD

**Issue by chdenat** [lgs1920/studio#70]

**Comment by chdenat** [comment]
```
POI.js:28  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at new POI (POI.js:28:29)
    at Journey.js:145:34
    at Map.forEach (<anonymous>)
    at Journey.deserialize (Journey.js:143:25)
    at Utils.updateJourney (Utils.js:134:33)
    at JourneySettings.jsx:189:33
```
